### New
POST http://127.0.0.1:3000/new

> {%
    const runId = response.body.run_id
    const Id = response.body.id
    client.global.set("runId", runId)
    client.global.set("Id", Id)
%}

### Edit
PUT  http://127.0.0.1:3000/edit/{{Id}}/{{runId}}

### View
GET  http://127.0.0.1:3000/{{Id}}/{{runId}}

### Approve
PUT  http://127.0.0.1:3000/approve/{{Id}}/{{runId}}